apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  config.alloy: |
{{ required "config value is required!" .Values.config | indent 4 }}
