apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: postgres:18.4 #https://github.com/docker-library/docs/tree/master/postgres
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - name: http
          containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: {{ required "name value is required!" .Values.name }}
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: password
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        volumeMounts:
          - name: ssv
            mountPath: /var/lib/postgresql/data
          - name: initdb
            mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: ssv
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}
      - name: initdb
        secret:
          secretName: {{ .Release.Name }}
          items:
            - key: initdbSql
              path: initdb.sql
