apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
stringData:
  username: {{ required "username value is required!" .Values.username }}
  password: {{ required "password value is required!" .Values.password }}
  exporterUsername: {{ required "exporterUsername value is required!" .Values.exporterUsername }}
  exporterPassword: {{ required "exporterPassword value is required!" .Values.exporterPassword }}
  initdbSql: {{ .Values.initSql | quote }}
  grantSql: |
    CREATE USER {{ .Values.exporterUsername }} WITH PASSWORD '{{ .Values.exporterPassword }}' CONNECTION LIMIT 3;

    GRANT pg_monitor TO {{ .Values.exporterUsername }};
