apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
stringData:
  username: {{ required "username value is required!" .Values.username }}
  password: {{ required "password value is required!" .Values.password }}
  initdbSql: {{ .Values.initSql | quote }}
