# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: {{ .Release.Name }}
#   namespace: {{ .Release.Namespace }}
# spec:
#   endpoints:
#     - port: metrics
#       path: /metrics
#   selector:
#     matchLabels:
#       app: {{ .Release.Name }}