# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: {{ .Release.Name }}-weekly-cleanup
#   namespace: {{ .Release.Namespace }}
# spec:
#   concurrencyPolicy: Forbid
#   failedJobsHistoryLimit: 1
#   successfulJobsHistoryLimit: 1
#   schedule: "30 6 * * 0" # At 06:30 on Sunday.
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#           - name: curlimage
#             image: curlimages/curl
#             imagePullPolicy: IfNotPresent
#             args:
#               - --request
#               - POST
#               - --fail
#               - {{ .Release.Name }}-postgres-backup-tool:8080/db/cleanup
#           restartPolicy: Never