apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - port: {{ required "appPort value is required!" .Values.appPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ required "managementPort value is required!" .Values.managementPort }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    app: {{ .Release.Name }}
