apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
stringData:
  password: {{ required "password value is required!" .Values.password | quote }}
  redis.conf: |
    requirepass {{ required "password value is required!" .Values.password | quote }}
    appendonly yes
    dir /data
