apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-route
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: letsencrypt
  routes:
    - kind: Rule
      match: Host(`{{ .Values.host }}`) && PathPrefix(`{{ .Values.basePath }}`)
      services:
        - kind: Service
          name: {{ .Release.Name }}
          namespace: {{ .Release.Namespace }}
          port: http