apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-route
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - {{ required "entryPoint value is required!" .Values.entryPoint }}
  routes:
    - kind: Rule
      {{ if .Values.basePath }}
      match: Host(`{{ required "host value is required!" .Values.host }}`) && PathPrefix(`{{ .Values.basePath }}`)
      {{ else }}
      match: Host(`{{ required "host value is required!" .Values.host }}`)
      {{ end }}
      services:
        - kind: Service
          name: {{ .Release.Name }}
          namespace: {{ .Release.Namespace }}
          port: http