apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config-files
  namespace: {{ .Release.Namespace }}
stringData:
{{- range .Values.configFile }}
  {{ .name }}: |-
{{ .data | b64dec | indent 4 }}
{{- end }}