apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ required "image value is required!" .Values.image }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - name: http
          containerPort: {{ required "appPort value is required!" .Values.appPort }}
        envFrom:
          - secretRef:
              name: {{ .Release.Name }}-env
        livenessProbe:
          httpGet:
            path: /?liveness
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /?readiness
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /?startup
            port: http
          failureThreshold: 20
          periodSeconds: 5