apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        azure.workload.identity/use: 'true'
      annotations:
        checksum/secret_env: {{ include (print $.Template.BasePath "/secret_env.yaml") . | sha256sum }}
        checksum/secret_config_files: {{ include (print $.Template.BasePath "/secret_config_files.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ required "image value is required!" .Values.image }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - name: http
          containerPort: 8080
        env:
          - name: BASE_PATH
            value: "{{ .Values.basePath }}"
        envFrom:
          - secretRef:
              name: {{ .Release.Name }}-env
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          failureThreshold: 30
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        volumeMounts:
{{- range .Values.configFile }}
          - name: secret-config-files
            mountPath: {{ .mountPath }}
            subPath: {{ .name }}
{{- end }}
{{- range .Values.persistentVolumeClaims }}
          - name: pvc-{{ .name }}
            mountPath: {{ .mountPath }}
{{- end }}
      volumes:
        - name: secret-config-files
          secret:
            secretName: {{ .Release.Name }}-config-files
{{- range .Values.persistentVolumeClaims }}
        - name: pvc-{{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
{{- end }}